#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course A\
llocation
#SBATCH -J pi
#SBATCH -o pi.stdout
#SBATCH -n 16
#SBATCH -p normal
#SBATCH -t 00:01:00
export OMP_NUM_THREADS=128
./pi