#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J nbody
#SBATCH -o nbody.stdout
#SBATCH -n 16
#SBATCH -p normal
#SBATCH -t 00:03:00
export OMP_NUM_THREADS=128
./nbody