#!/bin/bash
#SBATCH -A TG-CCR140008 # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J laplace
#SBATCH -o laplace.stdout
#SBATCH -n 16
#SBATCH -p normal
#SBATCH -t 00:01:00
export OMP_NUM_THREADS=128
./laplace